### ISSUE TITLE
可以提供一版由java的库吗

### ISSUE THREAD

**Issue by zuilintan** [lwj1994/LiveEventBus#1]

**Comment by zuilintan** [comment]
Kotlin中使用了很多语法糖, So Cool, 
只是对于Kotlin不熟练的人来说, 理解起来着实困难:)

**Comment by lwj1994** [comment]
> Kotlin中使用了很多语法糖, So Cool, 
> 只是对于Kotlin不熟练的人来说, 理解起来着实困难:)

有道理 作为基础酷确实优先使用java最好。我抽空用java写一下

**Comment by zuilintan** [comment]
hah， 都是夜猫子呀

**Comment by zuilintan** [comment]
期待一下:)

**Comment by lwj1994** [comment]
@zuilintan  在 sample 里 添加了 java 版本：https://github.com/lwj1994/LiveEventBus/blob/main/app/src/main/java/com/lwjlol/liveeventbus/javaversion/LiveEventBus.java
